#!/usr/bin/env python3
"""Build a small auditable Shadowrocket DIRECT rule-set from public sources."""

from __future__ import annotations

import io
import json
import re
import subprocess
import sys
import tarfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
LOCAL_RULE_DIR = ROOT / "client" / "shadowrocket"
RULE_DIR = LOCAL_RULE_DIR if LOCAL_RULE_DIR.is_dir() else ROOT
CONFIG_PATH = RULE_DIR / "sources.json"
OUTPUT_PATH = RULE_DIR / "direct-curated.list"
V2FLY_ARCHIVE = (
    "https://codeload.github.com/v2fly/domain-list-community/"
    "tar.gz/refs/heads/master"
)


def download(url: str) -> bytes:
    result = subprocess.run(
        [
            "curl",
            "-fsSL",
            "--retry",
            "3",
            "--retry-all-errors",
            "--connect-timeout",
            "15",
            "--max-time",
            "90",
            url,
        ],
        check=True,
        capture_output=True,
    )
    return result.stdout


def clean_line(raw: str) -> str:
    return raw.split("#", 1)[0].strip()


def rule_from_domain_line(raw: str) -> str | None:
    value = clean_line(raw)
    if not value or value.startswith("include:"):
        return None

    # V2Fly attributes follow the domain and do not affect this DIRECT aggregate.
    value = value.split()[0]
    if value.startswith("full:"):
        return f"DOMAIN,{value[5:]}"
    if value.startswith("keyword:"):
        return f"DOMAIN-KEYWORD,{value[8:]}"
    if value.startswith("regexp:"):
        return None
    if value.startswith("domain:"):
        value = value[7:]
    return f"DOMAIN-SUFFIX,{value}"


def load_v2fly_files() -> dict[str, str]:
    archive = tarfile.open(fileobj=io.BytesIO(download(V2FLY_ARCHIVE)), mode="r:gz")
    files: dict[str, str] = {}
    marker = "/data/"
    for member in archive.getmembers():
        if not member.isfile() or marker not in member.name:
            continue
        name = member.name.split(marker, 1)[1]
        if "/" in name:
            continue
        extracted = archive.extractfile(member)
        if extracted is not None:
            files[name] = extracted.read().decode("utf-8")
    return files


def expand_category(name: str, files: dict[str, str], seen: set[str]) -> set[str]:
    if name in seen:
        return set()
    if name not in files:
        raise KeyError(f"V2Fly category not found: {name}")
    seen.add(name)

    rules: set[str] = set()
    for raw in files[name].splitlines():
        value = clean_line(raw)
        if value.startswith("include:"):
            include_name = value.split()[0][len("include:") :]
            rules.update(expand_category(include_name, files, seen))
            continue
        rule = rule_from_domain_line(raw)
        if rule:
            rules.add(rule)
    return rules


def parse_shadowrocket_list(content: str) -> set[str]:
    valid = re.compile(r"^(DOMAIN|DOMAIN-SUFFIX|DOMAIN-KEYWORD),[^,]+$")
    return {
        clean_line(line)
        for line in content.splitlines()
        if valid.match(clean_line(line))
    }


def parse_domain_list(content: str) -> set[str]:
    return {
        rule
        for line in content.splitlines()
        if (rule := rule_from_domain_line(line)) is not None
    }


def main() -> int:
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    files = load_v2fly_files()
    rules: set[str] = set()
    seen: set[str] = set()

    for category in config["v2fly_categories"]:
        rules.update(expand_category(category, files, seen))
    for url in config["external_shadowrocket_lists"]:
        rules.update(parse_shadowrocket_list(download(url).decode("utf-8")))
    for url in config["external_domain_lists"]:
        rules.update(parse_domain_list(download(url).decode("utf-8")))

    ordered = sorted(rules, key=lambda item: (item.split(",", 1)[1], item))
    header = [
        "# Generated by scripts/build-shadowrocket_rules.py; do not edit.",
        "# Sources and selected categories: sources.json",
        f"# Rules: {len(ordered)}",
        "",
    ]
    OUTPUT_PATH.write_text("\n".join(header + ordered) + "\n", encoding="utf-8")
    print(f"Wrote {len(ordered)} rules to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
